# Default values for hello-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres

postgresql:
  enabled: true
  postgresqlUsername: myuser
  postgresqlPassword: passwd
  postgresqlDatabase: myapp
  service:
    port: "5432"
    name: postgres
  fullnameOverride: postgres