apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-my-app
  template:
    metadata:
      labels:
        app: hello-my-app
    spec:
      containers:
      - name: myapp
        image: myapp:v2
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: DATABASE_URI
        ports:
        - name: web
          containerPort: 8080
        readinessProbe :
          httpGet :
            port : 8080
            path : /health
          initialDelaySeconds: 10
          periodSeconds: 5